version: '2'
services:
  app:
    container_name: onlinecompanion
    restart: always
    build: .
    ports:
      - '80:3000'
    
    links:
      - mongo
   #   - angular
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  angular:
    container_name: angular
    restart: always
    build: frontend  
    ports: 
      - '4200:4200'
